name: Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup NodeJS 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run build:site

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/svelte/dist